spring.application.name=Research-Assistant

# Google Gemini API URL (without API key)
gemini.api.url=https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent

# Google API key only (replace with your actual key)
gemini.api.key=AIzaSyAp87hwNv0WUIpcZ8S-W6gZf8n4ca-RnNk
